// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeZhtfGam6dzZDCNJh9_hw6bJSGgnx8hA',
    appId: '1:1067772183738:web:1fd8fac221461304f8ae83',
    messagingSenderId: '1067772183738',
    projectId: 'hrmchat-67388',
    authDomain: 'hrmchat-67388.firebaseapp.com',
    storageBucket: 'hrmchat-67388.firebasestorage.app',
    measurementId: 'G-JFBCKNJ9VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxibJU6Ef7I36_x0IfP2iYYV-mDsePl3c',
    appId: '1:1067772183738:android:517c9efc24ba0651f8ae83',
    messagingSenderId: '1067772183738',
    projectId: 'hrmchat-67388',
    storageBucket: 'hrmchat-67388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1AbQVMiPOSmJ8GfVLQO01SH435j0Dep0',
    appId: '1:1067772183738:ios:b651890254ab5a77f8ae83',
    messagingSenderId: '1067772183738',
    projectId: 'hrmchat-67388',
    storageBucket: 'hrmchat-67388.firebasestorage.app',
    androidClientId: '1067772183738-kqdlmnvqqjp6nq8aeusbt56vh6scbvk2.apps.googleusercontent.com',
    iosClientId: '1067772183738-h2acp02sorcn7pj8f3dmb4psmc00r4cs.apps.googleusercontent.com',
    iosBundleId: 'com.hrmchat.app',
  );

}